[mgr]
layout         = [ 1, 4, 3 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = true
linemode       = "size_and_mtime"
show_hidden    = true
show_symlink   = true
scrolloff      = 8
# mouse_events   = nil
# title_format   = nil


[preview]
wrap = "yes"
tab_size = 2
max_width = 1080
max_height = 1920


[flavor]
dark = "tokyo-night"


[plugin]
prepend_previewers = [
{ url = "/Users/*/Documents/Fau/Movies/**", run = "noop" },
{ url = "/Users/*/Library/Mobile Documents/com~apple~CloudDocs/Documents/Fau/Movies/**", run = "noop" },
]

prepend_preloaders = [
{ url = "/Users/*/Documents/**", run = "noop" },
{ url = "/Users/*/Library/Mobile Documents/com~apple~CloudDocs/Documents/**", run = "noop" },
]

# ==================== Git ====================
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"


# ==================== Miem-ext ====================
[[plugin.prepend_fetchers]]
id   = "mime"
url  = "local://*"
run  = "mime-ext.local"
prio = "high"

[[plugin.prepend_fetchers]]
id   = "mime"
url  = "remote://*"
run  = "mime-ext.remote"
prio = "high"
